spring:
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root
    driverClassName: org.h2.Driver
  application:
    name: USER-SERVICE
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
    ddl-auto: update
  h2:
    console.enabled: true
  zipkin:
    base-url: http://zipkin:9411/
